import os
import requests
import json
import base64
import smtplib

from flask import Flask, request, abort
from email.mime.text import MIMEText
import hmac
from github import Github, GithubIntegration

app = Flask(__name__)

app_id = 821348

# Bot email info (probably should be stored as environment variables to prevent being tampered with)
bot_email = '@gmail.com'
# The password will (possibly) be stored as an environment variable BOT_EMAIL_PASSWORD
# bot_email_password = os.getenv("BOT_EMAIL_PASSWORD")
bot_email_password = ''
email_server = 'smtp.gmail.com'
email_server_port = 465

# Read the bot certificate
with open(os.path.normpath(os.path.expanduser("bot_key.pem")), "r") as cert_file:
    app_key = cert_file.read()

# Create an GitHub integration instance
git_integration = GithubIntegration(
    app_id,
    app_key,
)


# When we will have to send an email considering the time an issue is lingering, we would not have a label provided,
# so it is useful to keep that in mind when writing the main email sending function
def send_email(issue, config, label=None):
    email_info = config['email-info']
    recipients = email_info['recipients']

    try:
        # Establish the SMTP connection to specified server over a secure SSL connection
        smtp = smtplib.SMTP_SSL(email_server, email_server_port)
        # Log in on the SMTP server using the specified bot email address and bot email password
        smtp.login(bot_email, bot_email_password)

        # Create the email message for a label:
        # - if the developer wants to receive any kind of label generated by the ML model for the issue (by specifying
        #   config["email-info"]["which-labels"] == "all" in the config.json file)
        # OR
        # - if the generated label is not contained in the config["email-info"]["except-labels"] list (also specified
        #   by the developer), when the developer sets config["email-info"]["which-labels"] to "except" in the
        #   config.json file
        # After the email is created, send it using the SMTP connection to the specified recipients; also error handling
        if label is not None:
            if email_info["which-labels"] == "all" or (email_info["which-labels"] == "except" and label not in
                                                       email_info["except-labels"]):
                description = email_info['email-description-template']
                subject = email_info['email-subject-template']
                # - MIMEText used to create the email object
                # - description.format() replaces the three {} in the template of the email description string with the
                #   actual label, issue.number, issue.title values, in this order
                # - Therefore, any template that you use for the email description in the config.json file should contain
                #   three '{}' inside the string, the first one for the label that was associated with the issue, the
                #   second one for the issue number, and the third one for the issue title
                email = MIMEText(description.format(label, issue.number, issue.title))
                email['From'] = bot_email
                email['To'] = ', '.join(recipients)
                email['Subject'] = subject
                try:
                    smtp.sendmail(bot_email, recipients, email.as_string())
                    print("Email sent successfully!", flush=True)
                except smtplib.SMTPException as error:
                    print(f"SMTP mail sending error: {error}", flush=True)
                except Exception as error:
                    print(f"Mail sending error: {error}", flush=True)
            else:
                print(f"Generated label: {label} is contained in the 'except-labels' list specified in config.json, "
                      "no email sent", flush=True)
        # else Case: Send an email considering the other scenarios, other than label creation (e.g. lingering issue)
        # TO BE CREATED
    except smtplib.SMTPAuthenticationError as e:
        print("SMTP authentication error:", e, flush=True)
    except Exception as e:
        print("Authentication error:", e, flush=True)


def label_issue(issue, config, label=None):
    if label is None:
        # Call the model API to get the label
        url = config["endpoint"]
        headers = {
            "accept": "application/json",
            "Content-Type": "application/json",
        }
        data = {}
        if config["payload-type"] == "title":
            data["text"] = issue.title
        elif config["payload-type"] == "description":
            data["text"] = issue.body
        elif config["payload-type"] == "merged":
            data["text"] = issue.title + " " + issue.body
        elif config["payload-type"] == "both":
            label_title_and_desc(config, data, headers, issue, url)
            return
        result = requests.post(url, headers=headers, data=json.dumps(data)).json()
        label_location = config["label-location"]
        label = result[label_location]
        # Add the label to the issue
        issue.add_to_labels(label)
        # Send email if emails for labels are enabled in config.json
        if config["send-emails"] == True and config["when-to-send"] == "label":
            send_email(issue, config, label)
    else:
        # Simply add the label to the issue (for custom labels)
        issue.add_to_labels(label)
        # Don't think we should send an email when someone labels the issue manually


def label_title_and_desc(config, data, headers, issue, url):
    data["text"] = issue.title
    result = requests.post(url, headers=headers, data=json.dumps(data)).json()
    label_location = config["label-location"]
    title_label = result[label_location]
    data["text"] = issue.body
    result = requests.post(url, headers=headers, data=json.dumps(data)).json()
    label_location = config["label-location"]
    description_label = result[label_location]
    # Add the labels to the issue
    issue.add_to_labels("title: " + title_label)
    issue.add_to_labels("description: " + description_label)
    # Send email if emails for labels are enabled in config.json
    if config["send-emails"] == True and config["when-to-send"] == "label":
        if title_label == description_label:
            # Single email if the labels generated for both the title and the description of the issue are identical
            send_email(issue, config, title_label)
        else:
            # Separate emails if the labels generated for the title and the description of the issue are different
            send_email(issue, config, title_label)
            send_email(issue, config, description_label)


def handle_issue_comment_event(repo, payload, config):
    commenter = payload["comment"]["user"]["login"]
    if commenter == "technical-debt-mitigation-bot[bot]":
        return "ok"

    comment = repo.get_issue(number=payload["issue"]["number"]).get_comment(
        payload["comment"]["id"]
    )
    issue = repo.get_issue(number=payload["issue"]["number"])

    # comment body will be a command like "/tdbot label", "/tdbot help", etc. So we need to parse it
    command = comment.body.split(" ")
    if command[0] == "/tdbot":
        if command[1] == "label":
            if len(command) == 2:
                label_issue(issue, config)
            else:
                # add everything after the command to the label
                label = " ".join(command[2:])
                label_issue(issue, config, label)
        elif command[1] == "help":
            with open("help_message.txt", "r") as f:
                help_message = f.read()
            issue.create_comment(help_message)
        else:
            issue.create_comment("I don't understand your command. Please try again.")
    return "ok"


def handle_issue_creation_event(repo, payload, config):
    # check if the issue is newly created
    if payload["action"] != "opened":
        return "ok"

    issue = repo.get_issue(number=payload["issue"]["number"])
    # check if the repo is enabled for auto labeling
    if config["auto-label"] == True:
        label_issue(issue, config)
        return "ok"
    if config["initial-message"] == True:
        issue.create_comment(
            "This issue seems to document technical debt.\n\n"
            'You can label it with "/tdbot label"'
        )
    return "ok"


@app.route("/webhook", methods=["POST"])
def bot():
    # Validate the request is from GitHub
    secret = os.getenv("GITHUB_WEBHOOK_SECRET")
    signature = request.headers.get("X-Hub-Signature")
    if signature is None:
        abort(403)

    sha_name, signature = signature.split("=")
    if sha_name != "sha1":
        abort(501)

    mac = hmac.new(secret.encode("utf-8"), msg=request.data, digestmod="sha1")

    if not hmac.compare_digest(str(mac.hexdigest()), str(signature)):
        abort(403)

    # Get the event payload
    payload = request.json

    # Check if the event is a GitHub Issue Comment creation event
    payload_type = request.headers.get("X-GitHub-Event")
    owner = payload["repository"]["owner"]["login"]
    repo_name = payload["repository"]["name"]

    # Get a git connection as our bot
    git_connection = Github(
        login_or_token=git_integration.get_access_token(
            git_integration.get_installation(owner, repo_name).id
        ).token
    )

    repo = git_connection.get_repo(f"{owner}/{repo_name}")
    # if repo has config.json file use it, otherwise use the config.json file locally in the bot
    try:
        config_file = repo.get_contents("config.json")
        print("Using config file from the repo", flush=True)
        # decode the file
        config = json.loads(base64.b64decode(config_file.content).decode("utf-8"))
    except:
        with open("config.json", "r") as f:
            config = json.load(f)

    if payload_type == "issue_comment":
        return handle_issue_comment_event(repo, payload, config)
    elif payload_type == "issues":
        return handle_issue_creation_event(repo, payload, config)


if __name__ == "__main__":
    app.run(host="0.0.0.0", debug=True, port=5001)
