import smtplib

from email.mime.text import MIMEText

"""
Read the bot email info from a "bot_email.secret" file structured as follows:
- 1st line for the bot email address
- 2nd line for the bot email password (app password, not the usual email password)
"""
with open("bot_email.secret", "r") as secret_file:
    lines = secret_file.read().splitlines()

bot_email = lines[0]
bot_email_password = lines[1]
# This is the name that we want to be displayed as the sender to the recipients, instead of the actual bot email address
bot_name = 'Issue Classification Bot'
email_server = 'smtp.gmail.com'
email_server_port = 465

# Template string formatting function for replacing placeholders in the string
def format_template(issue, template, label=None):
    formatted_template = (template.replace('/issue_number', str(issue.number))
                                  .replace('/issue_author', issue.user.login)
                                  .replace('/issue_title', issue.title)
                                  .replace('/issue_description', issue.body)
                                  .replace('/issue_link', issue.html_url)
                                  .replace('/issue_repository', issue.repository.name)
                                  .replace('/issue_updated_at', str(issue.updated_at))
                                  .replace('/issue_created_at', str(issue.created_at)))
    if label:
        formatted_template = formatted_template.replace('/issue_label', label)
    return formatted_template

# Mail sending function
def send_email(issue_list, config, case, label=None):
    email_info = config['email-info']
    recipients = email_info['recipients']

    try:
        # Establish the SMTP connection to specified server over a secure SSL connection
        smtp = smtplib.SMTP_SSL(email_server, email_server_port)
        # Log in on the SMTP server using the specified bot email address and bot email password
        smtp.login(bot_email, bot_email_password)
    except smtplib.SMTPAuthenticationError as e:
        print("SMTP authentication error:", e, flush=True)
        return
    except Exception as e:
        print("Authentication error:", e, flush=True)
        return

    """
    Create the email message for a label:
    - if the practitioner wants to receive any kind of label generated by the ML model for the issue (by setting the
      "which-labels" field to "all" in the Bot/config.json file)
    OR
    - if the generated label is not contained in the list associated with the "except-labels" field (also specified 
      by the practitioner), when the practitioner sets the "which-labels" field to "except" in the Bot/config.json 
      file
    OR
    - if the generated label is contained in the list associated with the "specific-labels" field (also specified 
      by the practitioner), when the practitioner sets the "which-labels" field to "specific" in the Bot/config.json 
      file
    """
    # Label case
    if case == 0:
        if (email_info["which-labels"] == "all"
                or (email_info["which-labels"] == "except" and label not in email_info["except-labels"])
                or (email_info["which-labels"] == "specific" and label in email_info["specific-labels"])):
            description = email_info['email-description-template']['label']
            subject = email_info['email-subject-template']['label']
            issue = issue_list[0]

            # Replace placeholders in the email description template with actual data from the label and issue
            formatted_description = format_template(issue, description, label)

            # MIMEText used to create the email object
            email = MIMEText(formatted_description)
        else:
            if email_info["which-labels"] == "except":
                print(f"Generated label: {label} is contained in the 'except-labels' list specified in config.json,"
                      " no email sent", flush=True)
            if email_info["which-labels"] == "specific":
                print(f"Generated label: {label} is not contained in the 'specific-labels' list specified in config.json,"
                      " no email sent", flush=True)
            # Close the SMTP connection since no email will be sent
            smtp.quit()
            return

    """
    Create the email message for lingering issues
    """
    # Lingering case
    if case == 1:
        description_main = email_info['email-description-template']['lingering'][0]
        description_issue = email_info['email-description-template']['lingering'][1]
        subject = email_info['email-subject-template']['lingering']

        formatted_descriptions_issues = "".join([format_template(issue, description_issue) for issue in issue_list])
        formatted_description_main = description_main.format(formatted_descriptions_issues)

        email = MIMEText(formatted_description_main)

    # Feature under development case
    # if case == 2:
    # TO BE CREATED

    email['From'] = bot_name
    email['To'] = ', '.join(recipients)
    email['Subject'] = subject

    # After the email is created, send it using the SMTP connection to the specified recipients; also error handling
    try:
        smtp.sendmail(bot_email, recipients, email.as_string())
        print("Email sent successfully!", flush=True)
    except smtplib.SMTPException as error:
        print(f"SMTP mail sending error: {error}", flush=True)
    except Exception as error:
        print(f"Mail sending error: {error}", flush=True)

    # Close the SMTP connection after sending the email(s)
    smtp.quit()
    